apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-registry-pvc
  namespace: registry
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-retain
  resources:
    requests:
      storage: 50Gi
